chart/urls.py
from django.urls import path
from . import views

app_name = "chart"

urlpatterns = [
    # path("", views.get_chart_data, name="chart_list"),
    path("", views.home_view, name="home"),
    path("genres/", views.genres_view, name="genres"),
    path("history/", views.history_view, name="history"),
    path("about/", views.about_view, name="about"),
    path("chart_information/", views.chart_information_view, name="chart_information"),
    path("add_chart/", views.add_chart_view, name="add_chart"),
]

music_chart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("chart/", include("chart.urls", namespace="chart")),
]

chart/models.py
from django.db import models

# Create your models here.

class ChartModel(models.Model):
    title = models.CharField(max_length=50)
    artist = models.CharField(max_length=100)
    genres = models.CharField(max_length=50)
    ranking = models.IntegerField()
    release_date = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return f"{self.title} - {self.artist}"

chart/forms.py
from django import forms 
from .models import ChartModel

class ChartForm(forms.ModelForm):
    class Meta:
        model = ChartModel
        fields = ["title", "artist", "genres", "ranking", "release_date"]

    def __str__(self):
        return f"{self.title} - {self.artist}"

chart/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import requests
from .models import ChartModel
from .forms import ChartForm



def get_chart_data(request):
    API_KEY = "a027a9b7e2ffaeac2d5897f8b20f9348"
    url = f"https://ws.audioscrobbler.com/2.0/?method=tag.gettoptracks&tag=hiphop&api_key={API_KEY}&format=json"

    try:
        # APIリクエスト(タイムアウト5秒)
        response = requests.get(url, timeout=5)
        response.raise_for_status()
        data = response.json()
        tracks = data["tracks"]["track"]
    except Exception as e:
        # 失敗したらモックデータ
        tracks = [
            {"name": "Mock Song 1", "artist": {"name": "Mock Artist A"}},
            {"name": "Mock Song 2", "artist": {"name": "Mock Artist B"}},
        ]
    chart = []
    # 曲名とアーティストを10件表示
    for i, track in enumerate(tracks[:10], start=1):
        chart.append({
            "rank": i,
            "title": track["name"],
            "artist": track["artist"]["name"]
        })

    return render(request, "chart/chart_list.html", {"chart": chart})

def home_view(request):
    return render(request, "chart/home.html")

def genres_view(request):
    genres = ["HipHop", "R&B", "Rock", "Reggae", "Pop"]
    # genresのリストをgenres.htmlに渡す
    return render(request, "chart/genres.html", {"genres": genres})

def history_view(request):
    history = [
        {"title": "Mock Song 1", "artist": {"name": "Mock Artist A"}, "data": "2025-10-06"},
        {"title": "Mock Song 2", "artist": {"name": "Mock Artist B"}, "data": "2025-10-06"},
    ]
    # historyのリストをhistory.htmlに移す
    return render(request, "chart/history.html", {"history":history})

def about_view(request):
    # 固定情報は最初から辞書型
    context = {
        "app_name": "HipHop Chart Viewer",
        "author": "kumagai",
        "description": "このアプリはLast.fm APIから取得したHipHopチャートを自動で取得・表示します"
    }
    # 辞書で渡しているので引数は変数名でOK
    return render(request, "chart/about.html", context)

def chart_information_view(request):
    # ChartModelのデータを全て取得
    chart_information = ChartModel.objects.all()
    # テンプレートに渡す
    return render(request, "chart/chart_information.html", {"chart_information":chart_information})    

def add_chart_view(request):
    if request.method == "POST":
        form = ChartForm(request.POST)
        #入力が有効かどうかチェック
        if form.is_valid():
            # 保存
            form.save()
            # 保存後一覧ページへ推移
            return redirect("chart:chart_information")
    else:
        form = ChartForm()
    return render(request, "chart/add_chart.html", {"form": form})

chart/templates/chart/about.html
{% extends "base.html" %}

{% block content %}
<h1>アプリの概要</h1>
<p>アプリ名:{{ app_name }}</p>
<p>作成者:{{ author }}</p>
<p>説明:{{ description }}</p>

{% endblock content %}

chart/templates/chart/add_chart.html
{% extends "base.html" %}

{% block content %}
<h1>曲を追加する</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">保存</button>
</form>
{% endblock content %}

chart/templates/chart/chart_information.html
{% block content %}
<ul>
    {% for information in chart_information %}
        <li>{{ information }}</li>
    {% endfor %}
</ul>
{% endblock content %}

chart/templates/chart/chart_list.html
{% extends "base.html" %}

{% block content %}
  <body>
    {% comment %} ナビゲーションバー(bootstrap) {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'chart:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'chart:genres' %}">Genres</a>
              </li>
              <li class="nav-item">
                {% comment %} history.htmlのリンクを後で挿入 {% endcomment %}
                <a class="nav-link" href="{% url 'chart:history' %}">History</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'chart:about' %}">About</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    
    {% comment %} APIランキングTOP10取得 {% endcomment %}
    <h1>US Hip Hop <small>(Last.fm APIより取得)</small></h1>
    <ul>
      {% for song in chart %}
        <li>
          {{ song.rank }}位 - <strong>{{ song.title }}</strong> ({{ song.artist }})
        </li>
      {% empty %}
        <li>チャートデータを取得できませんでした。</li>
      {% endfor %}
    </ul>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
{% endblock content %}

chart/templates/chart/genres.html
{% extends "base.html" %}

{% block content %}
<h1>ジャンル一覧</h1>
<ul>
    {% for genre in genres %}
        <li>{{ genre }}</li>
    {% endfor %}
</ul>
{% endblock content %}

chart/templates/chart/history.html
{% extends "base.html" %}

{% block content %}
<h1>閲覧履歴</h1>
<li>{{ history }}</li>
{% endblock content %}

chart/templates/chart/home.html
{% extends "base.html" %}

{% block content %}
<h1>ホームページ</h1>
<p>HipHopチャートアプリへようこそ!</p>
{% endblock content %}

music_chart/templates/base.html
<!DOCTYPE html>
<html lang="ja" data-bs-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <title>US HipHop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    {% block header %}
    {% endblock header %}

    {% block content %}
    {% endblock content %}

  </body>
</html>